# config.yaml !!! IMPORTANT TO setup for your server
# What's your interface name
# What's gonna be your server host (DHCP) IP and TFTP IP
# What's gonna be your client's name and domain

# sudo sysctl -w net.ipv4.conf.br0.rp_filter=0
iface: "eth0"                 # host interface for manage DHCP
root_path: "./pxe_example/"   # PXE root folder
client_prefixIP: "192.168.2." # Client subnetwork <-- Same network as DHCP
server_ip: "192.168.2.1"      # Server IP <- interface's address IP for host
subnet_mask: "255.255.255.0"  # Subnet mask <- same as interface's mask
server_tftp: "192.168.2.1"    # TFTP IP   <- default host is DHCP and TFTP server
offset_seconds: 3600          # Host's timezone; client need to know what's timezone to prevent losing packets
client_name: "pxe_client"     # Client's name, perhaps need a little change cuz every client gonna get that name
domain_name: "local"          # Network's domain, for PXE

